name: Common Lib CI

on:
  pull_request:
    types:
      - opened
      - synchronize
      - edited
      - reopened

jobs:
  ci:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout repository
      uses: actions/checkout@v3

    - name: Use Node.js
      uses: actions/setup-node@v3
      with:
        node-version-file: '.nvmrc'
        cache: 'npm'

    - name: Install dependencies
      run: npm ci

    - name: Check linting issues
      run: npm run lint

    - name: Build Lib
      run: npm run build-lib
